// Curated structure only: period definitions and artist Wikipedia titles.
// All content (bios, dates, images, painting lists, stories, facts) is fetched
// from Wikipedia / Wikimedia Commons / Wikidata by ingest.mjs — nothing authored here.
//
// `category` overrides the default "Category:Paintings by {title}".
// `extraPaintings` are fallback Wikipedia article titles used when the category
// yields fewer than the target number of paintings (still validated against Wikipedia).

export const PERIODS = [
  {
    slug: "medieval",
    name: "Medieval & Gothic",
    start: 500,
    end: 1400,
    color: "#7d5a3c",
    artists: [
      { title: "Cimabue" },
      {
        title: "Duccio",
        extraPaintings: [
          "Maestà (Duccio)",
          "Rucellai Madonna",
          "Stoclet Madonna",
          "Crevole Madonna",
          "Madonna of the Franciscans",
          "Polyptych No. 28",
          "The Temptation of Christ on the Mountain (Duccio)",
          "Christ and the Samaritan Woman (Duccio)",
          "Healing of the Man Born Blind",
          "Annunciation (Duccio)",
        ],
      },
      { title: "Giotto" },
      { title: "Simone Martini" },
    ],
  },
  {
    slug: "renaissance",
    name: "Italian Renaissance",
    start: 1400,
    end: 1600,
    color: "#b08d57",
    artists: [
      { title: "Sandro Botticelli" },
      { title: "Leonardo da Vinci" },
      { title: "Michelangelo" },
      { title: "Raphael" },
      { title: "Titian" },
    ],
  },
  {
    slug: "northern-renaissance",
    name: "Northern Renaissance",
    start: 1430,
    end: 1580,
    color: "#6e7f3e",
    artists: [
      { title: "Jan van Eyck" },
      { title: "Hieronymus Bosch" },
      { title: "Albrecht Dürer" },
      { title: "Pieter Bruegel the Elder" },
    ],
  },
  {
    slug: "baroque",
    name: "Baroque",
    start: 1600,
    end: 1750,
    color: "#8c2d2d",
    artists: [
      { title: "Caravaggio" },
      { title: "Peter Paul Rubens" },
      { title: "Artemisia Gentileschi" },
      { title: "Diego Velázquez" },
      { title: "Rembrandt" },
      { title: "Johannes Vermeer" },
    ],
  },
  {
    slug: "rococo",
    name: "Rococo",
    start: 1700,
    end: 1780,
    color: "#c98ba3",
    artists: [
      { title: "Antoine Watteau" },
      { title: "François Boucher" },
      { title: "Jean-Honoré Fragonard" },
    ],
  },
  {
    slug: "neoclassicism",
    name: "Neoclassicism",
    start: 1760,
    end: 1830,
    color: "#7a8ca3",
    artists: [
      { title: "Angelica Kauffman" },
      { title: "Jacques-Louis David" },
      { title: "Jean-Auguste-Dominique Ingres" },
    ],
  },
  {
    slug: "romanticism",
    name: "Romanticism",
    start: 1780,
    end: 1850,
    color: "#5d4a78",
    artists: [
      { title: "Francisco Goya" },
      { title: "J. M. W. Turner" },
      { title: "Caspar David Friedrich" },
      { title: "Théodore Géricault" },
      { title: "Eugène Delacroix" },
    ],
  },
  {
    slug: "realism",
    name: "Realism",
    start: 1840,
    end: 1880,
    color: "#4f6652",
    artists: [
      { title: "Jean-François Millet" },
      { title: "Gustave Courbet" },
      { title: "Édouard Manet" },
      { title: "Winslow Homer" },
    ],
  },
  {
    slug: "impressionism",
    name: "Impressionism",
    start: 1860,
    end: 1895,
    color: "#5e8fae",
    artists: [
      { title: "Camille Pissarro" },
      { title: "Edgar Degas" },
      { title: "Claude Monet" },
      { title: "Pierre-Auguste Renoir" },
      { title: "Mary Cassatt" },
    ],
  },
  {
    slug: "post-impressionism",
    name: "Post-Impressionism",
    start: 1885,
    end: 1910,
    color: "#c97b3d",
    artists: [
      { title: "Paul Cézanne" },
      { title: "Paul Gauguin" },
      { title: "Vincent van Gogh" },
      { title: "Georges Seurat" },
      { title: "Henri de Toulouse-Lautrec" },
    ],
  },
  {
    slug: "expressionism",
    name: "Expressionism",
    start: 1905,
    end: 1935,
    color: "#b8452f",
    artists: [
      { title: "Edvard Munch" },
      { title: "Wassily Kandinsky" },
      { title: "Franz Marc" },
      { title: "Ernst Ludwig Kirchner" },
      {
        title: "Egon Schiele",
        extraPaintings: [
          "Portrait of Wally",
          "Death and the Maiden (Schiele)",
          "Self-Portrait with Physalis",
          "Portrait of Eduard Kosmack",
          "House with Shingle Roof",
          "Four Trees (Egon Schiele)",
          "Seated Woman with Bent Knees",
        ],
      },
    ],
  },
  {
    slug: "cubism",
    name: "Cubism",
    start: 1907,
    end: 1925,
    color: "#857d6b",
    artists: [
      { title: "Pablo Picasso" },
      { title: "Georges Braque" },
      { title: "Juan Gris" },
      { title: "Jean Metzinger" },
      { title: "Robert Delaunay" },
    ],
  },
  {
    slug: "surrealism",
    name: "Surrealism",
    start: 1920,
    end: 1955,
    color: "#4e7d78",
    artists: [
      { title: "Max Ernst" },
      { title: "Joan Miró" },
      { title: "René Magritte" },
      { title: "Salvador Dalí" },
      { title: "Frida Kahlo" },
    ],
  },
  {
    slug: "abstract-expressionism",
    name: "Abstract Expressionism",
    start: 1943,
    end: 1965,
    color: "#33415c",
    artists: [
      { title: "Willem de Kooning" },
      { title: "Jackson Pollock" },
      { title: "Mark Rothko" },
    ],
  },
  {
    slug: "pop-art",
    name: "Pop Art",
    start: 1955,
    end: 1975,
    color: "#c94f7c",
    artists: [
      {
        title: "Jasper Johns",
        extraPaintings: [
          "Flag (painting)",
          "Three Flags",
          "White Flag (painting)",
          "False Start (painting)",
          "Map (painting)",
          "Target with Four Faces",
          "Painted Bronze",
          "Regrets (Jasper Johns)",
        ],
      },
      { title: "Andy Warhol" },
      { title: "Roy Lichtenstein" },
    ],
  },
  {
    slug: "contemporary",
    name: "Post-War & Contemporary",
    start: 1945,
    end: 2026,
    color: "#3d8b6e",
    artists: [
      {
        title: "Francis Bacon (artist)",
        category: "Category:Paintings by Francis Bacon",
      },
      { title: "Jean-Michel Basquiat" },
      {
        title: "David Hockney",
        extraPaintings: [
          "A Bigger Splash",
          "Portrait of an Artist (Pool with Two Figures)",
          "American Collectors",
          "Mr and Mrs Clark and Percy",
          "Peter Getting Out of Nick's Pool",
          "A Bigger Grand Canyon",
          "The Splash",
          "Garrowby Hill",
        ],
      },
      {
        title: "Banksy",
        category: "Category:Works by Banksy",
        extraPaintings: [
          "Girl with Balloon",
          "Love Is in the Bin",
          "Devolved Parliament",
          "Show Me the Monet",
          "Game Changer (painting)",
          "Slave Labour (mural)",
          "Kissing Coppers",
          "Well Hung Lover",
          "One Nation Under CCTV",
          "Mobile Lovers",
          "Spy Booth",
        ],
      },
    ],
  },
];
