// Curated structure only: period definitions and artist Wikipedia titles.
// All content (bios, dates, images, painting lists, stories, facts) is fetched
// from Wikipedia / Wikimedia Commons / Wikidata by ingest.mjs — nothing authored here.
//
// `category` overrides the default "Category:Paintings by {title}".
// `extraPaintings` are fallback Wikipedia article titles used when the category
// yields fewer than the target number of paintings (still validated against Wikipedia).

export const PERIODS = [
  {
    slug: "medieval",
    name: "Medieval & Gothic",
    start: 500,
    end: 1400,
    color: "#7d5a3c",
    artists: [
      { title: "Cimabue" },
      {
        title: "Duccio",
        extraPaintings: [
          "Maestà (Duccio)",
          "Rucellai Madonna",
          "Stoclet Madonna",
          "Crevole Madonna",
          "Madonna of the Franciscans",
          "Polyptych No. 28",
          "The Temptation of Christ on the Mountain (Duccio)",
          "Christ and the Samaritan Woman (Duccio)",
          "Healing of the Man Born Blind",
          "Annunciation (Duccio)",
        ],
      },
      { title: "Giotto" },
      { title: "Simone Martini" },
    ],
  },
  {
    slug: "renaissance",
    name: "Italian Renaissance",
    start: 1400,
    end: 1600,
    color: "#b08d57",
    artists: [
      { title: "Sandro Botticelli" },
      { title: "Leonardo da Vinci" },
      { title: "Michelangelo" },
      { title: "Raphael" },
      { title: "Titian" },
    ],
  },
  {
    slug: "northern-renaissance",
    name: "Northern Renaissance",
    start: 1430,
    end: 1580,
    color: "#6e7f3e",
    artists: [
      { title: "Jan van Eyck" },
      { title: "Hieronymus Bosch" },
      { title: "Albrecht Dürer" },
      { title: "Pieter Bruegel the Elder" },
    ],
  },
  {
    slug: "baroque",
    name: "Baroque",
    start: 1600,
    end: 1750,
    color: "#8c2d2d",
    artists: [
      { title: "Caravaggio" },
      { title: "Peter Paul Rubens" },
      { title: "Artemisia Gentileschi" },
      { title: "Diego Velázquez" },
      { title: "Rembrandt" },
      { title: "Johannes Vermeer" },
    ],
  },
  {
    slug: "rococo",
    name: "Rococo",
    start: 1700,
    end: 1780,
    color: "#c98ba3",
    artists: [
      { title: "Antoine Watteau" },
      { title: "François Boucher" },
      { title: "Jean-Honoré Fragonard" },
    ],
  },
  {
    slug: "neoclassicism",
    name: "Neoclassicism",
    start: 1760,
    end: 1830,
    color: "#7a8ca3",
    artists: [
      { title: "Angelica Kauffman" },
      { title: "Jacques-Louis David" },
      { title: "Jean-Auguste-Dominique Ingres" },
    ],
  },
  {
    slug: "romanticism",
    name: "Romanticism",
    start: 1780,
    end: 1850,
    color: "#5d4a78",
    artists: [
      { title: "Francisco Goya" },
      { title: "J. M. W. Turner" },
      { title: "Caspar David Friedrich" },
      { title: "Théodore Géricault" },
      { title: "Eugène Delacroix" },
      {
        title: "William Blake",
        category: "Category:Paintings by William Blake",
        extraPaintings: [
          "The Ancient of Days",
          "The Ghost of a Flea",
          "Newton (Blake)",
          "The Great Red Dragon paintings",
          "Nebuchadnezzar (Blake)",
        ],
      },
    ],
  },
  {
    slug: "ukiyo-e",
    name: "Japanese Ukiyo-e",
    start: 1780,
    end: 1860,
    color: "#1f567a",
    artists: [
      {
        title: "Hokusai",
        category: "Category:Works by Hokusai",
        extraPaintings: [
          "The Great Wave off Kanagawa",
          "Fine Wind, Clear Morning",
          "Rainstorm Beneath the Summit",
          "A Tour of the Waterfalls of the Provinces",
          "Oceans of Wisdom",
        ],
      },
      {
        title: "Hiroshige",
        category: "Category:Works by Utagawa Hiroshige",
        extraPaintings: [
          "The Fifty-three Stations of the Tōkaidō",
          "One Hundred Famous Views of Edo",
          "Sudden Shower over Shin-Ōhashi bridge and Atake",
          "The Plum Garden in Kameido",
        ],
      },
    ],
  },
  {
    slug: "realism",
    name: "Realism",
    start: 1840,
    end: 1880,
    color: "#4f6652",
    artists: [
      { title: "Jean-François Millet" },
      { title: "Gustave Courbet" },
      { title: "Édouard Manet" },
      { title: "Winslow Homer" },
      { title: "John Singer Sargent" },
    ],
  },
  {
    slug: "impressionism",
    name: "Impressionism",
    start: 1860,
    end: 1895,
    color: "#5e8fae",
    artists: [
      { title: "Camille Pissarro" },
      { title: "Edgar Degas" },
      { title: "Claude Monet" },
      { title: "Pierre-Auguste Renoir" },
      { title: "Mary Cassatt" },
      { title: "Berthe Morisot" },
    ],
  },
  {
    slug: "post-impressionism",
    name: "Post-Impressionism",
    start: 1885,
    end: 1910,
    color: "#c97b3d",
    artists: [
      { title: "Paul Cézanne" },
      { title: "Paul Gauguin" },
      { title: "Vincent van Gogh" },
      { title: "Georges Seurat" },
      { title: "Henri de Toulouse-Lautrec" },
      { title: "Gustav Klimt" },
      { title: "Henri Rousseau" },
    ],
  },
  {
    slug: "art-nouveau-symbolism",
    name: "Art Nouveau & Symbolism",
    start: 1890,
    end: 1914,
    color: "#a88532",
    artists: [
      {
        title: "Alphonse Mucha",
        category: "Category:Paintings by Alphonse Mucha",
        extraPaintings: [
          "The Slav Epic",
          "The Four Seasons (Mucha)",
          "Gismonda",
          "Zodiac (Mucha)",
        ],
      },
      {
        title: "Hilma af Klint",
        category: "Category:Paintings by Hilma af Klint",
        extraPaintings: [
          "The Ten Largest",
          "Altarpieces (Hilma af Klint)",
          "The Swan (Hilma af Klint)",
          "Evolution (Hilma af Klint)",
        ],
      },
      {
        title: "Odilon Redon",
        category: "Category:Paintings by Odilon Redon",
        extraPaintings: [
          "The Cyclops (Redon)",
          "Ophelia (Redon)",
          "Pandora (Redon)",
          "Buddha (Redon)",
        ],
      },
    ],
  },
  {
    slug: "fauvism",
    name: "Fauvism",
    start: 1904,
    end: 1910,
    color: "#d94e28",
    artists: [
      { title: "Henri Matisse" },
      { title: "André Derain" },
      { title: "Maurice de Vlaminck" },
      { title: "Kees van Dongen" },
    ],
  },
  {
    slug: "expressionism",
    name: "Expressionism",
    start: 1905,
    end: 1935,
    color: "#b8452f",
    artists: [
      { title: "Edvard Munch" },
      { title: "Wassily Kandinsky" },
      { title: "Franz Marc" },
      { title: "Ernst Ludwig Kirchner" },
      { title: "Amedeo Modigliani" },
      { title: "Paul Klee" },
      {
        title: "Egon Schiele",
        extraPaintings: [
          "Portrait of Wally",
          "Death and the Maiden (Schiele)",
          "Self-Portrait with Physalis",
          "Portrait of Eduard Kosmack",
          "House with Shingle Roof",
          "Four Trees (Egon Schiele)",
          "Seated Woman with Bent Knees",
        ],
      },
    ],
  },
  {
    slug: "cubism",
    name: "Cubism",
    start: 1907,
    end: 1925,
    color: "#857d6b",
    artists: [
      { title: "Pablo Picasso" },
      { title: "Georges Braque" },
      { title: "Juan Gris" },
      { title: "Jean Metzinger" },
      { title: "Robert Delaunay" },
    ],
  },
  {
    slug: "futurism",
    name: "Futurism",
    start: 1909,
    end: 1930,
    color: "#a83248",
    artists: [
      { title: "Umberto Boccioni" },
      { title: "Giacomo Balla" },
      { title: "Gino Severini" },
    ],
  },
  {
    slug: "de-stijl-suprematism",
    name: "De Stijl & Suprematism",
    start: 1913,
    end: 1931,
    color: "#1d4e89",
    artists: [
      { title: "Piet Mondrian" },
      { title: "Kazimir Malevich" },
      { title: "Theo van Doesburg" },
    ],
  },
  {
    slug: "dada",
    name: "Dada",
    start: 1916,
    end: 1924,
    color: "#4a4e51",
    artists: [
      { title: "Marcel Duchamp" },
      { title: "Francis Picabia" },
      { title: "Hannah Höch" },
    ],
  },
  {
    slug: "surrealism",
    name: "Surrealism",
    start: 1920,
    end: 1955,
    color: "#4e7d78",
    artists: [
      { title: "Max Ernst" },
      { title: "Joan Miró" },
      { title: "René Magritte" },
      { title: "Salvador Dalí" },
      { title: "Frida Kahlo" },
      { title: "Marc Chagall" },
    ],
  },
  {
    slug: "metaphysical-mathematical",
    name: "Metaphysical & Mathematical Art",
    start: 1910,
    end: 1965,
    color: "#3a506b",
    artists: [
      {
        title: "M. C. Escher",
        category: "Category:Works by M. C. Escher",
        extraPaintings: [
          "Relativity (M. C. Escher)",
          "Drawing Hands",
          "Waterfall (M. C. Escher)",
          "Ascending and Descending",
          "Hand with Reflecting Sphere",
          "Sky and Water I",
          "Metamorphosis I",
          "Metamorphosis II",
          "House of Stairs",
          "Belvedere (M. C. Escher)",
          "Reptiles (M. C. Escher)",
          "Bond of Union",
        ],
      },
      {
        title: "Giorgio de Chirico",
        extraPaintings: [
          "The Song of Love (de Chirico)",
          "The Mystery and Melancholy of a Street",
          "The Nostalgia of the Infinite",
          "The Disquieting Muses",
          "Guglielmo Marconi (portrait)",
        ],
      },
    ],
  },
  {
    slug: "american-modernism",
    name: "American Modernism",
    start: 1920,
    end: 1950,
    color: "#466365",
    artists: [
      { title: "Edward Hopper" },
      { title: "Grant Wood" },
      { title: "Jacob Lawrence" },
      { title: "Thomas Hart Benton (painter)" },
    ],
  },
  {
    slug: "golden-age-illustration",
    name: "Golden Age Illustration & Realism",
    start: 1900,
    end: 1970,
    color: "#6b583a",
    artists: [
      {
        title: "N. C. Wyeth",
        category: "Category:Works by N. C. Wyeth",
        extraPaintings: [
          "The Giant (Wyeth)",
          "Treasure Island",
          "Robin Hood",
          "The Boy's King Arthur",
          "Island Funeral",
          "In the Dark of the Moon",
          "The Hunter (Wyeth)",
          "Stand and Deliver (Wyeth)",
        ],
      },
      {
        title: "Andrew Wyeth",
        extraPaintings: [
          "Christina's World",
          "Wind from the Sea (painting)",
          "Winter 1946",
          "Braids (painting)",
          "Trodden Weed",
          "Siri (painting)",
          "Master Bedroom (painting)",
        ],
      },
      {
        title: "Maxfield Parrish",
        category: "Category:Works by Maxfield Parrish",
        extraPaintings: [
          "Daybreak (painting)",
          "Ecstasy (painting)",
          "The Lantern Bearers (Parrish)",
          "Stars (Parrish)",
        ],
      },
    ],
  },
  {
    slug: "abstract-expressionism",
    name: "Abstract Expressionism",
    start: 1943,
    end: 1965,
    color: "#33415c",
    artists: [
      { title: "Willem de Kooning" },
      { title: "Jackson Pollock" },
      { title: "Mark Rothko" },
      { title: "Georgia O'Keeffe" },
    ],
  },
  {
    slug: "color-field",
    name: "Color Field & Minimalism",
    start: 1950,
    end: 1975,
    color: "#286b7b",
    artists: [
      { title: "Helen Frankenthaler" },
      { title: "Cy Twombly" },
      { title: "Yves Klein" },
      { title: "Frank Stella" },
    ],
  },
  {
    slug: "pop-art",
    name: "Pop Art",
    start: 1955,
    end: 1975,
    color: "#c94f7c",
    artists: [
      {
        title: "Jasper Johns",
        extraPaintings: [
          "Flag (painting)",
          "Three Flags",
          "White Flag (painting)",
          "False Start (painting)",
          "Map (painting)",
          "Target with Four Faces",
          "Painted Bronze",
          "Regrets (Jasper Johns)",
        ],
      },
      { title: "Andy Warhol" },
      { title: "Roy Lichtenstein" },
      { title: "Keith Haring" },
    ],
  },
  {
    slug: "contemporary",
    name: "Post-War & Contemporary",
    start: 1945,
    end: 2026,
    color: "#3d8b6e",
    artists: [
      {
        title: "Francis Bacon (artist)",
        category: "Category:Paintings by Francis Bacon",
      },
      { title: "Jean-Michel Basquiat" },
      {
        title: "David Hockney",
        extraPaintings: [
          "A Bigger Splash",
          "Portrait of an Artist (Pool with Two Figures)",
          "American Collectors",
          "Mr and Mrs Clark and Percy",
          "Peter Getting Out of Nick's Pool",
          "A Bigger Grand Canyon",
          "The Splash",
          "Garrowby Hill",
        ],
      },
      { title: "Yayoi Kusama" },
      { title: "Gerhard Richter" },
      {
        title: "Banksy",
        category: "Category:Works by Banksy",
        extraPaintings: [
          "Girl with Balloon",
          "Love Is in the Bin",
          "Devolved Parliament",
          "Show Me the Monet",
          "Game Changer (painting)",
          "Slave Labour (mural)",
          "Kissing Coppers",
          "Well Hung Lover",
          "One Nation Under CCTV",
          "Mobile Lovers",
          "Spy Booth",
        ],
      },
    ],
  },
];
